import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider, SignedIn, UserButton } from "@clerk/nextjs";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        cbody className={`${geistSans.variable} ${geistMono.variable} antialiased`}e
          header className="fixed top-3 right-3 z-50"e
            SignedIne
              UserButton afterSignOutUrl="/" appearance={{ variables: { borderRadius: "8px" } }} /e
            /SignedIne
          /headere
          div className="min-h-screen"e{children}/dive
        /bodye
      </html>
    </ClerkProvider>
  );
}
